name: Build and Deploy to ECR

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx for multi-platform builds (if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Configure AWS credentials using GitHub secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1  # Change this to your desired AWS region

      # Step 4: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Step 5: Build and push Docker image to ECR with 'latest' tag
      - name: Build and Push to ECR
        run: |
          # Define your ECR repository URL
          ECR_REPO_URL=024848475874.dkr.ecr.us-west-1.amazonaws.com/database-apis

          # Build the Docker image
          docker build -t database-apis .

          # Tag the image with the 'latest' tag
          docker tag database-apis:latest $ECR_REPO_URL:latest

          # Push the image to ECR with the 'latest' tag
          docker push $ECR_REPO_URL:latest

      # Step 6: Logout from Amazon ECR
      - name: Logout from Amazon ECR
        run: docker logout 024848475874.dkr.ecr.us-west-1.amazonaws.com
